name: Windows (i386/x86_64/armv7/aarch64)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-i386:
    runs-on: windows-latest
    name: mingw32-i386
    env:
      # TODO would be nice to build this here as well
      #SDL_VERSION: 2.30.9
      #SDL_SHA256: 24b574f71c87a763f50704bbb630cbe38298d544a1f890f099a4696b1d6beba4
      SDL12_VERSION: 1.2.15
      SDL12_SHA256: d6d316a793e5e348155f0dd93b979798933fb98aa1edebcc108829d6474aad00
      FLAC_VERSION: 1.4.3
      FLAC_SHA256: 6c58e69cd22348f441b861092b825e591d0b822e106de6eb0ee4d05d27205b70
      LIBOGG_VERSION: 1.3.5
      LIBOGG_SHA256: c4d91be36fc8e54deae7575241e03f4211eb102afb3fc0775fbbc1b740016705
      UTF8PROC_VERSION: 2.9.0
      UTF8PROC_SHA256: bd215d04313b5bc42c1abedbcb0a6574667e31acee1085543a232204e36384c4
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          path: schism

        # setup msys2 to make use of its nice dev tools...
        # we also need the headers it provides for
        # Media Foundation and they provide a prebuilt
        # SDL2 binary as well
      - name: 'Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw32
          update: true
          install: git mingw-w64-i686-toolchain mingw-w64-i686-flac mingw-w64-i686-SDL2 libtool autoconf automake make zip unzip dos2unix patch
          location: 'C:\\msys2'

      - name: 'Retrieve runner temp directory'
        id: temp
        run: |
          cd schism
          echo "temp=$(cygpath -u "$RUNNER_TEMP")" >> $GITHUB_OUTPUT
          echo "wpath=$RUNNER_TEMP" >> $GITHUB_OUTPUT
          cd ..

        # FIXME store this in RUNNER_TEMP instead
      - name: 'Cache MinGW'
        id: cache-i386-mingw
        uses: actions/cache@v4
        with:
          path: 'C:\\MinGW'
          key: mingw32-i386-install

      - name: 'Cache dependencies'
        id: cache-i386-dependencies
        uses: actions/cache@v4
        with:
          path: '${{ steps.temp.outputs.wpath }}\\i386prefix'
          key: mingw32-i386-dependencies-SDL12_${{ env.SDL12_VERSION }}-FLAC_${{ env.FLAC_VERSION }}-LIBOGG_${{ env.LIBOGG_VERSION }}-UTF8PROC_${{ env.UTF8PROC_VERSION }}

        # grab a (quite old) version of mingw32 so that we can
        # target extremely old Windows versions that mingw-w64
        # doesn't care about (and doesn't work on)
      - name: 'Setup MinGW'
        if: steps.cache-i386-mingw.outputs.cache-hit != 'true'
        run: |
          wget --no-check-certificate -O mingw-get.zip "https://sourceforge.net/projects/mingw/files/Installer/mingw-get/mingw-get-0.6.2-beta-20131004-1/mingw-get-0.6.2-mingw32-beta-20131004-1-bin.zip/download"
          mkdir "/c/MinGW"
          unzip mingw-get.zip -d"/c/MinGW"
          rm mingw-get.zip
          "/c/MinGW/bin/mingw-get.exe" install mingw32-base-bin msys-base-bin

      - name: 'Add MinGW binaries to PATH'
        run: |
          echo "$(cygpath -w "/c/MinGW/bin")" >> $GITHUB_PATH
          echo "$(cygpath -w "/c/MinGW/msys/1.0/bin")" >> $GITHUB_PATH

      - name: 'Download SDL 1.2 sources'
        if: steps.cache-i386-dependencies.outputs.cache-hit != 'true'
        run: |
          which gcc
          wget -O "SDL-$SDL12_VERSION.tar.gz" https://www.libsdl.org/release/SDL-$SDL12_VERSION.tar.gz
          echo "$SDL12_SHA256  SDL-$SDL12_VERSION.tar.gz" | sha256sum -c -
          tar xvf "SDL-$SDL12_VERSION.tar.gz"
          cd "SDL-$SDL12_VERSION"
          ./autogen.sh
          cd ..

      - name: 'Build SDL 1.2'
        if: steps.cache-i386-dependencies.outputs.cache-hit != 'true'
        env:
          RUNNER_TEMP_CYGPATH: ${{ steps.temp.outputs.temp }}
        shell:
          "bash.exe {0}"
        run: |
          cd SDL-$SDL12_VERSION
          CC="mingw32-gcc.exe" CPPFLAGS="-I$RUNNER_TEMP_CYGPATH/i386prefix/include" LDFLAGS="-L$RUNNER_TEMP_CYGPATH/i386prefix/lib" ./configure --prefix="$RUNNER_TEMP_CYGPATH/i386prefix" || (cat config.log && false)
          make
          make install
          cd ..

      - name: 'Download libflac and libogg sources'
        if: steps.cache-i386-dependencies.outputs.cache-hit != 'true'
        run: |
          wget -O libogg-$LIBOGG_VERSION.tar.xz "https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-$LIBOGG_VERSION.tar.xz" || wget -O libogg-$LIBOGG_VERSION.tar.xz "https://github.com/xiph/ogg/releases/download/v$LIBOGG_VERSION/libogg-$LIBOGG_VERSION.tar.xz"
          echo "$LIBOGG_SHA256  libogg-$LIBOGG_VERSION.tar.xz" | sha256sum -c -
          tar xvf "libogg-$LIBOGG_VERSION.tar.xz"
          cd libogg-$LIBOGG_VERSION
          autoreconf -i
          cd ..

          wget -O flac-$FLAC_VERSION.tar.xz "https://ftp.osuosl.org/pub/xiph/releases/flac/flac-$FLAC_VERSION.tar.xz" || wget -O flac-$FLAC_VERSION.tar.xz "https://github.com/xiph/flac/releases/download/$FLAC_VERSION/flac-$FLAC_VERSION.tar.xz"
          echo "$FLAC_SHA256  flac-$FLAC_VERSION.tar.xz" | sha256sum -c -
          tar xvf "flac-$FLAC_VERSION.tar.xz"
          cd "flac-$FLAC_VERSION"
          patch -p1 < ../schism/.github/patches/FLAC/1-win32-revert-utime64.patch
          autoreconf -i
          cd ..

      - name: 'Build libflac'
        if: steps.cache-i386-dependencies.outputs.cache-hit != 'true'
        env:
          RUNNER_TEMP_CYGPATH: ${{ steps.temp.outputs.temp }}
        shell:
          "bash.exe {0}"
        run: |
          cd libogg-$LIBOGG_VERSION
          mkdir build
          cd build
          CC="mingw32-gcc.exe" CPPFLAGS="-I$RUNNER_TEMP_CYGPATH/i386prefix/include" LDFLAGS="-L$RUNNER_TEMP_CYGPATH/i386prefix/lib" ../configure --prefix="$RUNNER_TEMP_CYGPATH/i386prefix"
          make
          make install
          cd ../../flac-$FLAC_VERSION
          mkdir build
          cd build
          CC="mingw32-gcc.exe" CPPFLAGS="-I$RUNNER_TEMP_CYGPATH/i386prefix/include" LDFLAGS="-L$RUNNER_TEMP_CYGPATH/i386prefix/lib" ../configure --prefix="$RUNNER_TEMP_CYGPATH/i386prefix" --with-ogg-includes="$RUNNER_TEMP_CYGPATH/i386prefix/include" --with-ogg-libraries="$RUNNER_TEMP_CYGPATH/i386prefix/lib" --disable-programs --disable-examples --disable-cpplibs
          make
          make install
          cd ../..

      - name: 'Download utf8proc'
        if: steps.cache-i386-dependencies.outputs.cache-hit != 'true'
        run: |
          wget -O "utf8proc-$UTF8PROC_VERSION.tar.gz" "https://github.com/JuliaStrings/utf8proc/releases/download/v$UTF8PROC_VERSION/utf8proc-$UTF8PROC_VERSION.tar.gz"
          echo "$UTF8PROC_SHA256  utf8proc-$UTF8PROC_VERSION.tar.gz" | sha256sum -c -
          tar xvf "utf8proc-$UTF8PROC_VERSION.tar.gz"

          cd "utf8proc-$UTF8PROC_VERSION"
          patch -p1 < "../schism/.github/patches/utf8proc/3-windows.patch"
          cd ..

      - name: 'Build utf8proc'
        if: steps.cache-i386-dependencies.outputs.cache-hit != 'true'
        env:
          RUNNER_TEMP_CYGPATH: ${{ steps.temp.outputs.temp }}
        shell:
          "bash.exe {0}"
        run: |
          cd utf8proc-$UTF8PROC_VERSION
          make CC="mingw32-gcc.exe"
          cp "utf8proc.h" "$RUNNER_TEMP_CYGPATH/i386prefix/include"
          cp "libutf8proc-3.dll" "$RUNNER_TEMP_CYGPATH/i386prefix/lib/libutf8proc-3.dll"
          cd ..
        
      - name: 'Get date of latest commit'
        id: date
        run: |
          cd schism
          echo "date=$(git log -n 1 --date=short --format=format:%cd | sed 's/\(....\)-\(..\)-\(..\).*/\1\2\3/')" >> $GITHUB_OUTPUT
          cd ..

      - name: 'autoreconf'
        run: |
          cd schism
          autoreconf -i
          cd ..

      - name: 'Compile package'
        env:
          RUNNER_TEMP_CYGPATH: ${{ steps.temp.outputs.temp }}
        shell:
          "bash.exe {0}"
        run: |
          ls /c/msys2/msys64/mingw32
          cd schism
          mkdir build
          cd build
          MEDIAFOUNDATION_CFLAGS="-I/c/msys2/msys64/mingw32/include" CPPFLAGS="-I$RUNNER_TEMP_CYGPATH/i386prefix/include" LDFLAGS="-L$RUNNER_TEMP_CYGPATH/i386prefix/lib" CC="mingw32-gcc.exe" UTF8PROC_CFLAGS="-I$RUNNER_TEMP_CYGPATH/i386prefix/include" UTF8PROC_LIBS="-L$RUNNER_TEMP_CYGPATH/i386prefix/lib -lutf8proc-3" SDL12_CFLAGS="-I$RUNNER_TEMP_CYGPATH/i386prefix/include/SDL" SDL12_LIBS="-L$RUNNER_TEMP_CYGPATH/i386prefix/lib -lSDL" FLAC_CFLAGS="-I$RUNNER_TEMP_CYGPATH/i386prefix/include" FLAC_LIBS="-L$RUNNER_TEMP_CYGPATH/i386prefix/lib -lFLAC -logg -lm" SDL2_CFLAGS="-I/c/msys2/msys64/mingw32/include/SDL2" SDL2_LIBS="-L/c/msys2/msys64/mingw32/lib -lSDL2" ../configure --with-flac --with-sdl2 --with-sdl12
          make
          strip schismtracker.exe
          cp schismtracker.exe ../..
          cd ../..

      - name: 'Create package'
        env:
          RUNNER_TEMP_CYGPATH: ${{ steps.temp.outputs.temp }}
        run: |
          cp "$RUNNER_TEMP_CYGPATH/i386prefix/bin/SDL.dll" .
          cp "/c/msys2/msys64/mingw32/bin/SDL2.dll" .
          cp "$RUNNER_TEMP_CYGPATH/i386prefix/bin/libFLAC-12.dll" .
          cp "$RUNNER_TEMP_CYGPATH/i386prefix/bin/libogg-0.dll" .
          cp "$RUNNER_TEMP_CYGPATH/i386prefix/lib/libutf8proc-3.dll" .
          strip SDL.dll
          strip SDL2.dll
          strip "libFLAC-12.dll"
          strip "libogg-0.dll"
          strip "libutf8proc-3.dll"
          cp schism/docs/configuration.md schism/README.md schism/COPYING .
          wget https://raw.githubusercontent.com/xiph/flac/master/COPYING.Xiph
          unix2dos COPYING.Xiph COPYING README.md configuration.md

      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: schismtracker-${{ steps.date.outputs.date }}-mingw32-i386
          path: |
            schismtracker.exe
            SDL.dll
            SDL2.dll
            libFLAC-12.dll
            libogg-0.dll
            libutf8proc-3.dll
            COPYING
            COPYING.Xiph
            README.md
            configuration.md

  build-others:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw32, target: x86_64, stdlib: msvcrt, cflags: '-O2', ldflags: '' }
          - { sys: mingw32, target: armv7, stdlib: msvcrt, cflags: '-O2', ldflags: '' }
          - { sys: mingw32, target: aarch64, stdlib: ucrt, cflags: '-O2', ldflags: '' }
    name: ${{ matrix.sys }}-${{ matrix.target }}
    env:
      LLVM_MINGW_VERSION: 20240518
      SDL_VERSION: 2.30.10
      SDL_SHA256: f59adf36a0fcf4c94198e7d3d776c1b3824211ab7aeebeb31fe19836661196aa
      SDL12_VERSION: 1.2.15
      SDL12_SHA256: d6d316a793e5e348155f0dd93b979798933fb98aa1edebcc108829d6474aad00
      FLAC_VERSION: 1.4.3
      FLAC_SHA256: 6c58e69cd22348f441b861092b825e591d0b822e106de6eb0ee4d05d27205b70
      LIBOGG_VERSION: 1.3.5
      LIBOGG_SHA256: c4d91be36fc8e54deae7575241e03f4211eb102afb3fc0775fbbc1b740016705
      UTF8PROC_VERSION: 2.9.0
      UTF8PROC_SHA256: bd215d04313b5bc42c1abedbcb0a6574667e31acee1085543a232204e36384c4
      NVDA_CONTROLLER_VERSION: 2024.4.1
      TARGET: ${{ matrix.target }}
      SYS: ${{ matrix.sys }}
      STDLIB: ${{ matrix.stdlib }}
      CFLAGS: ${{ matrix.cflags }}
      LDFLAGS: ${{ matrix.ldflags }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          path: schism

      - name: 'Install unix2dos'
        run: |
          sudo apt-get install -y dos2unix

      - name: 'Cache llvm-mingw'
        id: cache-llvm-mingw
        uses: actions/cache@v4
        with:
          path: '/home/runner/llvm-mingw'
          key: windows-${{ matrix.stdlib }}-llvm-mingw-${{ env.LLVM_MINGW_VERSION }}

      - name: 'Cache dependencies'
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: '/home/runner/prefix'
          key: windows-${{ matrix.sys }}-${{ matrix.target }}-${{ matrix.stdlib }}-dependencies-SDL_${{ env.SDL_VERSION }}-SDL12_${{ env.SDL12_VERSION }}-FLAC_${{ env.FLAC_VERSION }}-LIBOGG_${{ env.LIBOGG_VERSION }}-UTF8PROC_${{ env.UTF8PROC_VERSION }}

      - name: 'Grab llvm-mingw'
        if: steps.cache-llvm-mingw.outputs.cache-hit != 'true'
        run: |
          curl -L "https://github.com/mstorsjo/llvm-mingw/releases/download/$LLVM_MINGW_VERSION/llvm-mingw-$LLVM_MINGW_VERSION-$STDLIB-ubuntu-20.04-x86_64.tar.xz" | tar xJvf - -C "$HOME"
          mv "$HOME/llvm-mingw-$LLVM_MINGW_VERSION-$STDLIB-ubuntu-20.04-x86_64" "$HOME/llvm-mingw"

<<<<<<< HEAD
      - name: 'Grab NVDAController'
        if: env.TARGET != 'armv7'
        run: |
          export CARCH=$(([ $TARGET == aarch64 ] && echo arm64) || ([ $TARGET == i686 ] && echo x86) || ([ $TARGET == x86_64 ] && echo x64))
          cd "$HOME"
          curl -L "https://www.nvaccess.org/files/nvda/releases/stable/nvda_${NVDA_CONTROLLER_VERSION}_controllerClient.zip" > "controller.zip"
          unzip controller.zip -d controller
          [ -d prefix/bin ] || mkdir -p prefix/bin
          mv controller/$CARCH/nvdaControllerClient.dll prefix/bin

      - name: 'Download SDL 1.2 sources'
        if: env.TARGET == 'i686' && steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          wget -O "SDL-$SDL12_VERSION.tar.gz" https://www.libsdl.org/release/SDL-$SDL12_VERSION.tar.gz
          echo "$SDL12_SHA256  SDL-$SDL12_VERSION.tar.gz" | sha256sum -c -
          tar xvf "SDL-$SDL12_VERSION.tar.gz"

      - name: 'Build SDL 1.2'
        if: env.TARGET == 'i686' && steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          export PATH="$HOME/llvm-mingw/bin:$PATH"
          cd SDL-$SDL12_VERSION
          ./configure --host="$TARGET-w64-$SYS" --prefix="$HOME/prefix"
          make
          make install
          cd ..

=======
>>>>>>> 4f358e2e3c1affd321c07e3fcc4286c8005a3d87
      - name: 'Download SDL2 sources'
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          wget -O "SDL2-$SDL_VERSION.tar.gz" https://www.libsdl.org/release/SDL2-$SDL_VERSION.tar.gz || wget -O "SDL2-$SDL_VERSION.tar.gz" https://github.com/libsdl-org/SDL/releases/download/release-$SDL_VERSION/SDL2-$SDL_VERSION.tar.gz
          echo "$SDL_SHA256  SDL2-$SDL_VERSION.tar.gz" | sha256sum -c -
          tar xvf "SDL2-$SDL_VERSION.tar.gz"

      - name: 'Build SDL2'
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          export PATH="$HOME/llvm-mingw/bin:$PATH"
          cd SDL2-$SDL_VERSION
          ./configure --host="$TARGET-w64-$SYS" --prefix="$HOME/prefix"
          make
          make install
          cd ..

      - name: 'Download libflac and libogg sources'
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          wget -O libogg-$LIBOGG_VERSION.tar.xz "https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-$LIBOGG_VERSION.tar.xz" || wget -O libogg-$LIBOGG_VERSION.tar.xz "https://github.com/xiph/ogg/releases/download/v$LIBOGG_VERSION/libogg-$LIBOGG_VERSION.tar.xz"
          echo "$LIBOGG_SHA256  libogg-$LIBOGG_VERSION.tar.xz" | sha256sum -c -
          tar xvf "libogg-$LIBOGG_VERSION.tar.xz"

          wget -O flac-$FLAC_VERSION.tar.xz "https://ftp.osuosl.org/pub/xiph/releases/flac/flac-$FLAC_VERSION.tar.xz" || wget -O flac-$FLAC_VERSION.tar.xz "https://github.com/xiph/flac/releases/download/$FLAC_VERSION/flac-$FLAC_VERSION.tar.xz"
          echo "$FLAC_SHA256  flac-$FLAC_VERSION.tar.xz" | sha256sum -c -
          tar xvf "flac-$FLAC_VERSION.tar.xz"

      - name: 'Build libflac'
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          export PATH="$HOME/llvm-mingw/bin:$PATH"
          cd libogg-$LIBOGG_VERSION
          mkdir build
          cd build
          ../configure --host="$TARGET-w64-$SYS" --prefix="$HOME/prefix"
          make
          make install
          cd ../../flac-$FLAC_VERSION
          mkdir build
          cd build
          ../configure --host="$TARGET-w64-$SYS" --prefix="$HOME/prefix" --disable-programs --disable-examples --disable-cpplibs
          make
          make install
          cd ../..

      - name: 'Download utf8proc'
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          wget -O "utf8proc-$UTF8PROC_VERSION.tar.gz" "https://github.com/JuliaStrings/utf8proc/releases/download/v$UTF8PROC_VERSION/utf8proc-$UTF8PROC_VERSION.tar.gz"
          echo "$UTF8PROC_SHA256  utf8proc-$UTF8PROC_VERSION.tar.gz" | sha256sum -c -
          tar xvf "utf8proc-$UTF8PROC_VERSION.tar.gz"

      - name: 'Build utf8proc'
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          export PATH="$HOME/llvm-mingw/bin:$PATH"
          cd utf8proc-$UTF8PROC_VERSION
          mkdir build
          cd build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX="$HOME/prefix" -DCMAKE_C_COMPILER="$TARGET-w64-$SYS-clang" -DCMAKE_SYSTEM_NAME="Windows"
          make
          make install
          cd ../..

      - name: 'Checkout SRAL'
        uses: actions/checkout@v4
        with:
          repository: 'm1maker/SRAL'
          path: SRAL

      - name: 'Build SRAL'
        run: |
          export PATH="$HOME/llvm-mingw/bin:$PATH"
          cd SRAL
          mkdir build
          cd build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX="$HOME/prefix" -DCMAKE_C_COMPILER="$TARGET-w64-$SYS-clang" -DCMAKE_SYSTEM_NAME="Windows"
          make
          make install
          cd ../..

      - name: 'Get date of latest commit'
        id: date
        run: |
          cd schism
          echo "date=$(git log -n 1 --date=short --format=format:%cd | sed 's/\(....\)-\(..\)-\(..\).*/\1\2\3/')" >> $GITHUB_OUTPUT
          cd ..

      - name: 'Build package'
        run: |
          export PATH="$HOME/llvm-mingw/bin:$PATH"
          export PKG_CONFIG_PATH="$HOME/prefix/lib/pkgconfig"
          cd schism
          autoreconf -I"$HOME/prefix/share/aclocal" -i
          mkdir build
          cd build
          ../configure --host="$TARGET-w64-$SYS" --prefix="$HOME/prefix" --with-flac --with-sdl2 CPPFLAGS="-I$HOME/prefix/include" LDFLAGS="-L$HOME/prefix/lib"
          make
          "$TARGET-w64-$SYS-strip" -g schismtracker.exe
          cp schismtracker.exe ../..
          cd ../..
          cp "$HOME/prefix/bin/SDL2.dll" .
          cp "$HOME/prefix/bin/libFLAC-12.dll" .
          cp "$HOME/prefix/bin/libogg-0.dll" .
          cp "$HOME/prefix/bin/libSRAL.dll" .
          cp $HOME/llvm-mingw/$TARGET-w64-$SYS/bin/*.dll .
          [ -f $HOME/prefix/bin/nvdaControllerClient.dll ] && cp $HOME/prefix/bin/nvdaControllerClient.dll .
          "$TARGET-w64-$SYS-strip" -g "SDL2.dll"
          "$TARGET-w64-$SYS-strip" -g "libFLAC-12.dll"
          "$TARGET-w64-$SYS-strip" -g "libogg-0.dll"
          "$TARGET-w64-$SYS-strip" -g "libSRAL.dll"
          cp schism/docs/accessibility.md schism/docs/configuration.md schism/README.md schism/COPYING .
          wget https://raw.githubusercontent.com/xiph/flac/master/COPYING.Xiph
          unix2dos COPYING.Xiph COPYING README.md configuration.md accessibility.md

      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: schismtracker-${{ steps.date.outputs.date }}-${{ matrix.sys }}-${{ matrix.target }}
          path: |
            schismtracker.exe
<<<<<<< HEAD
            SDL.dll
=======
>>>>>>> 4f358e2e3c1affd321c07e3fcc4286c8005a3d87
            SDL2.dll
            libFLAC-12.dll
            libogg-0.dll
            libSRAL.dll
            nvdaControllerClient.dll
            COPYING
            COPYING.Xiph
            README.md
            configuration.md
            accessibility.md
